version: 2

before:
  hooks:
    - go mod tidy

# Skip building binaries since this is a library
builds:
  - skip: true

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}
    files:
      - LICENSE
      - README.md
      - examples/**/*

checksum:
  algorithm: sha256

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
  # Reference: https://github.com/gin-gonic/gin/blob/master/.goreleaser.yaml
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: "Bug fixes"
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: "Enhancements"
      regexp: "^.*chore[(\\w)]*:+.*$"
      order: 2
    - title: "Refactor"
      regexp: "^.*refactor[(\\w)]*:+.*$"
      order: 3
    - title: "Build process updates"
      regexp: ^.*?(build|ci)(\(.+\))??!?:.+$
      order: 4
    - title: "Documentation updates"
      regexp: ^.*?docs?(\(.+\))??!?:.+$
      order: 5
    - title: Others
      order: 999

release:
  github:
    owner: sudosz
    name: tg-state-manager
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## tg-state-manager {{ .Version }} ({{ .Date }})
    
    This release includes various improvements and bug fixes.
  footer: |
    ## Installation
    
    ```
    go get github.com/sudosz/tg-state-manager@{{ .Tag }}
    ```
    
signs:
  - artifacts: checksum